import React, { ReactNode } from "react";
import Footer from "./Footer";
import Head from "next/head";
import Player from "./Music/Player/Player";
import Sidebar from "./Sidebar";

interface Props {
  // ReactNode represents any props that come into the children component
  children?: ReactNode;
  title?: String;
  themeData: any;
}

const Layout = ({ title, children, themeData }: Props) => {
  return (
    <>
      <Head>
        <title>
          {/* The title name is dynamic depending on the specific page */}
          {title
            ? title + " | 24/7 Vasteloavend Muzieek"
            : `${themeData?.attributes?.Name} | 24/7 Vasteloavend Muzieek`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen md:flex relative">
        <Sidebar themeData={themeData} />
        <div>
          {children}
          <Footer />
        </div>
      </main>
    </>
  );
};

export default Layout;
